name = "ai-brainstorm-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# Enable Node.js compatibility
# https://developers.cloudflare.com/workers/runtime-apis/nodejs/
compatibility_flags = [ "nodejs_compat" ]


[dev]
# Expose the dev server on localhost:8787
port = 8787
# live_reload = true # Typically enabled by default

# Bindings for development
[vars]
# OPENAI_API_KEY = "your_dev_openai_key"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "ai_brainstorm"
database_id = "ai_brainstorm_db" # Replace with actual ID after creating the database

# Example KV Namespace binding for dev
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# preview_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# Example D1 Database binding for dev
# [[d1_databases]]
# binding = "DB"
# database_name = "my-database-dev"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
# preview_database_id = "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy" 